Improved functionality

diff --git a/calcgr b/calcgr
--- a/calcgr
+++ b/calcgr
@@ -10,12 +10,15 @@ recalculate_grade() {
 
 read_grades() {
     while IFS= read -r line; do
-	echo "$line"
+        echo "$line"
     done < saved_data.txt
 }
 
 clear_grades() {
-    echo "one last something"
+    while IFS= read -r line; do
+        echo "" >> saved_data.txt
+    done < saved_data.txt
+    echo "File cleared"
 }
 
 echo -e "\nSelect from one of the following options:"
@@ -25,29 +28,45 @@ echo "  [2] Read pre-existing grades"
 echo "  [3] Clear all grades"
 echo "  [x] Exit"
 echo -n "User Input: "
-read user_input
+read user_option
 
-while : ; do    # do while user_input != "x"
-    case $user_input in
-	0)    # Calculating new grade
-	    echo "Calculating new grade"
-	    ;;
-	1)    # Recalculating pre-existing grades
-	    echo "Recalculating pre-existing grade"
-	    ;;
-	2)    # Reading previous grades
-	    echo "Reading pre-existing grades"
-	    read_grades | less
-	    ;;
-	3)    # Clearing all grades
-	    echo "Clearing all grades"
-	    ;;
-	x)    # Exiting
-	    echo -e "\nExiting..."
-	    ;;
-	*)    # default, if option given is invalid
-	    echo "Invalid option, please try again"
-	    ;;
+while : ; do    # do while user_option != "x"
+    case $user_option in
+    0)    # Calculating new grade
+        echo "Calculating new grade"
+        ;;
+    1)    # Recalculating pre-existing grades
+        echo "Recalculating pre-existing grade"
+        ;;
+    2)    # Reading previous grades
+        read_grades | less
+        ;;
+    3)    # Clearing all grades
+        echo -n "Type CLEAR to confirm or [x] to exit: "
+        read user_choice
+        while : ; do
+            case $user_choice in
+                CLEAR)
+                    echo "Clearing file"
+                    clear_grades
+                    ;;
+                x)
+                    echo "Exiting..."
+                    ;;
+                *)
+                    echo "Invalid option"
+                    ;;
+             esac
+             [[ user_choice == "x" ]] || break
+        done
+        ;;
+    x)    # Exiting
+        echo -e "\nExiting..."
+        ;;
+    *)    # default, if option given is invalid
+        echo "Invalid option, please try again"
+        ;;
     esac
-    [[ user_input == "x" ]] || break
-done	  
+    [[ user_option == "x" ]] || break
+done      
+echo ""
